import FWCore.ParameterSet.Config as cms

mergedLeptonIDImage = cms.EDAnalyzer("MergedLeptonIDImage",
  isMC = cms.bool(True),
  srcEle = cms.InputTag("slimmedElectrons"),
  srcPv = cms.InputTag("offlineSlimmedPrimaryVertices"),
  pileupSummary = cms.InputTag("slimmedAddPileupInfo"),
  addGsfTrkMap = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","eleAddGsfTrk"),
  addPackedCandMap = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","eleAddPackedCand"),
  trkIsoMap = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","eleTrkPtIso"),
  dPerpIn = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","dPerpIn"),
  dEtaInSeed2nd = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","dEtaInSeed2nd"),
  dPhiInSC2nd = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","dPhiInSC2nd"),
  alphaTrack = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","alphaTrack"),
  alphaCalo = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","alphaCalo"),
  normalizedDParaIn = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","normalizedDParaIn"),
  union5x5covIeIe = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","union5x5covIeIe"),
  union5x5covIeIp = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","union5x5covIeIp"),
  union5x5dEtaIn = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","union5x5dEtaIn"),
  union5x5dPhiIn = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","union5x5dPhiIn"),
  union5x5Energy = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","union5x5Energy"),
  packedPFcand = cms.InputTag("packedPFCandidates"),
  genptc = cms.InputTag("prunedGenParticles"),
  generator = cms.InputTag("generator"),
  ESrecHits = cms.InputTag("reducedEgamma","reducedESRecHits"),
  EErecHits = cms.InputTag("reducedEgamma","reducedEERecHits"),
  emObjectProducer = cms.InputTag("slimmedElectrons"),
  triggerResults = cms.InputTag("TriggerResults","","HLT"),
  triggerObjects = cms.InputTag("slimmedPatTrigger"),
  trigList = cms.vstring(
    "HLT_Mu9_IP6*",
    "HLT_Mu12_IP6*"
  ),
  PUrwgt = cms.FileInPath("ZprimeTo4l/MergedLepton/data/BPH_Mu9_or_Mu12_IP6_PUrwgt.root"),
  IPthresTag = cms.double(6.),
  dzThres = cms.double(0.1),
  d0Thres = cms.double(0.06),
  probThres = cms.double(10e-2),
  cosAlpha2dThres = cms.double(0.95),
  ptThresTag = cms.double(9.),
  ptThresK = cms.double(3.5),
  imageSize = cms.int32(7),
  ESimageSize = cms.int32(3)
)
