import FWCore.ParameterSet.Config as cms

mergedEleBkgMvaInput = cms.EDAnalyzer("MergedEleBkgMvaInput",
  srcEle=cms.InputTag("slimmedElectrons"),
  srcPv=cms.InputTag("offlineSlimmedPrimaryVertices"),
  trkIsoMap=cms.InputTag("modifiedHEEPIDVarValueMaps2nd","eleTrkPtIso"),
  ecalIsoMap=cms.InputTag("modifiedEcalRecHitIsolationScone2nd","EcalRecHitIso"),
  addGsfTrkMap = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","eleAddGsfTrk"),
  conversions = cms.InputTag("reducedEgamma:reducedConversions"),
  generator = cms.InputTag("generator"),
  lheEvent = cms.InputTag("externalLHEProducer"),
  beamSpot = cms.InputTag("offlineBeamSpot"),
  EBrecHits = cms.InputTag("reducedEgamma","reducedEBRecHits"),
  EErecHits = cms.InputTag("reducedEgamma","reducedEERecHits"),
  ptThres = cms.double(50.),
  select0J = cms.bool(False),
  selectHT = cms.bool(False),
  maxHT = cms.double(70.),
  posCalcLog = cms.PSet( T0_barl      = cms.double(7.4),
                         T0_endc      = cms.double(3.1),
                         T0_endcPresh = cms.double(1.2),
                         LogWeighted  = cms.bool(True),
                         W0           = cms.double(4.2),
                         X0           = cms.double(0.89) ),
  posCalcLinear = cms.PSet( T0_barl      = cms.double(7.4),
                            T0_endc      = cms.double(3.1),
                            T0_endcPresh = cms.double(1.2),
                            LogWeighted  = cms.bool(False),
                            W0           = cms.double(4.2),
                            X0           = cms.double(0.89) )
)
