import FWCore.ParameterSet.Config as cms

mergedLeptonIDProducer = cms.EDProducer("MergedLeptonIDProducer",
  srcEle=cms.InputTag("slimmedElectrons"),
  srcPv=cms.InputTag("offlineSlimmedPrimaryVertices"),
  beamSpot = cms.InputTag("offlineBeamSpot"),
  trkIsoMap=cms.InputTag("ModifiedHEEPIDVarValueMaps","eleTrkPtIso"),
  ecalIsoMap=cms.InputTag("ModifiedEcalRecHitIsolationScone","EcalRecHitIso"),
  nrSatCrysMap = cms.InputTag("ModifiedHEEPIDVarValueMaps","eleNrSaturateIn5x5"),
  addGsfTrkMap = cms.InputTag("ModifiedHEEPIDVarValueMaps","eleAddGsfTrk"),
  rho=cms.InputTag("fixedGridRhoFastjetAll"),
  vetoConv = cms.bool(True),
  etThresEB = cms.double(200.),
  etThresEE = cms.double(150.),
  minEt = cms.double(50.),
  xgbPathDR1Et2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR1Et2_EB_20UL16.xml"),
  meanstdPathDR1Et2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR1Et2_EB_20UL16.csv"),
  cutDR1Et2EB=cms.double(0.866),
  xgbPathDR2Et1EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR2Et1_EB_20UL16.xml"),
  meanstdPathDR2Et1EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR2Et1_EB_20UL16.csv"),
  cutDR2Et1EB=cms.double(0.840),
  xgbPathDR2Et2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR2Et2_EB_20UL16.xml"),
  meanstdPathDR2Et2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR2Et2_EB_20UL16.csv"),
  cutDR2Et2EB=cms.double(0.326),
  xgbPathDR2Et1EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR2Et1_EE_20UL16.xml"),
  meanstdPathDR2Et1EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR2Et1_EE_20UL16.csv"),
  cutDR2Et1EE=cms.double(0.762),
  xgbPathDR2Et2EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR2Et2_EE_20UL16.xml"),
  meanstdPathDR2Et2EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/DR2Et2_EE_20UL16.csv"),
  cutDR2Et2EE=cms.double(0.666),
  xgbPathBkgEt2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/NoneEt2_EB_20UL16.xml"),
  meanstdPathBkgEt2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/NoneEt2_EB_20UL16.csv"),
  cutBkgEt2EB=cms.double(0.678)
)
