import FWCore.ParameterSet.Config as cms

mergedEleSigMvaInput = cms.EDAnalyzer("MergedEleSigMvaInput",
  srcEle=cms.InputTag("slimmedElectrons"),
  srcGenPtc=cms.InputTag("prunedGenParticles"),
  srcPv=cms.InputTag("offlineSlimmedPrimaryVertices"),
  trkIsoMap=cms.InputTag("modifiedHEEPIDVarValueMaps2nd","eleTrkPtIso"),
  ecalIsoMap=cms.InputTag("modifiedEcalRecHitIsolationScone2nd","EcalRecHitIso"),
  addGsfTrkMap = cms.InputTag("modifiedHEEPIDVarValueMaps2nd","eleAddGsfTrk"),
  conversions = cms.InputTag("reducedEgamma:reducedConversions"),
  beamSpot = cms.InputTag("offlineBeamSpot"),
  generator = cms.InputTag("generator"),
  EBrecHits = cms.InputTag("reducedEgamma","reducedEBRecHits"),
  EErecHits = cms.InputTag("reducedEgamma","reducedEERecHits"),
  ptThres=cms.double(20.),
  ptThres2nd = cms.double(10.),
  drThres=cms.double(0.3),
  posCalcLog = cms.PSet( T0_barl      = cms.double(7.4),
                         T0_endc      = cms.double(3.1),
                         T0_endcPresh = cms.double(1.2),
                         LogWeighted  = cms.bool(True),
                         W0           = cms.double(4.2),
                         X0           = cms.double(0.89) ),
  posCalcLinear = cms.PSet( T0_barl      = cms.double(7.4),
                            T0_endc      = cms.double(3.1),
                            T0_endcPresh = cms.double(1.2),
                            LogWeighted  = cms.bool(False),
                            W0           = cms.double(4.2),
                            X0           = cms.double(0.89) )
)
