import FWCore.ParameterSet.Config as cms

mergedLeptonIDProducer = cms.EDProducer("MergedLeptonIDProducer",
  srcEle=cms.InputTag("slimmedElectrons"),
  srcPv=cms.InputTag("offlineSlimmedPrimaryVertices"),
  beamSpot = cms.InputTag("offlineBeamSpot"),
  trkIsoMap=cms.InputTag("ModifiedHEEPIDVarValueMaps","eleTrkPtIso"),
  ecalIsoMap=cms.InputTag("ModifiedEcalRecHitIsolationScone","EcalRecHitIso"),
  nrSatCrysMap = cms.InputTag("ModifiedHEEPIDVarValueMaps","eleNrSaturateIn5x5"),
  addGsfTrkMap = cms.InputTag("ModifiedHEEPIDVarValueMaps","eleAddGsfTrk"),
  rho=cms.InputTag("fixedGridRhoFastjetAll"),
  vetoConv = cms.bool(True),
  etThresEB = cms.double(200.),
  etThresEE = cms.double(150.),
  minEt = cms.double(50.),
  xgbPathDR1Et2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr1_et2_EB.xml"),
  meanstdPathDR1Et2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr1_et2_EB.csv"),
  cutDR1Et2EB=cms.double(0.8),
  xgbPathDR2Et1EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr2_et1_EB.xml"),
  meanstdPathDR2Et1EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr2_et1_EB.csv"),
  cutDR2Et1EB=cms.double(0.8),
  xgbPathDR2Et2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr2_et2_EB.xml"),
  meanstdPathDR2Et2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr2_et2_EB.csv"),
  cutDR2Et2EB=cms.double(0.8),
  xgbPathDR1Et2EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr1_et2_EE.xml"),
  meanstdPathDR1Et2EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr1_et2_EE.csv"),
  cutDR1Et2EE=cms.double(0.8),
  xgbPathDR2Et1EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr2_et1_EE.xml"),
  meanstdPathDR2Et1EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr2_et1_EE.csv"),
  cutDR2Et1EE=cms.double(0.8),
  xgbPathDR2Et2EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr2_et2_EE.xml"),
  meanstdPathDR2Et2EE=cms.FileInPath("ZprimeTo4l/MergedLepton/data/dr2_et2_EE.csv"),
  cutDR2Et2EE=cms.double(0.8),
  xgbPathBkgEt2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/bkg_et2_EB.xml"),
  meanstdPathBkgEt2EB=cms.FileInPath("ZprimeTo4l/MergedLepton/data/bkg_et2_EB.csv"),
  cutBkgEt2EB=cms.double(0.8)
)
